name: Build and push docker images to the Github Docker registry

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build a Docker image and push it to docker.pkg.github.com
        run: |
          VERSION="1.0"
          docker build -t docker.pkg.github.com/mirzachi/dockerized-llvm-toolchain/base:${VERSION} -f base/Dockerfile .
          docker login docker.pkg.github.com --username mirzachi --password ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/mirzachi/dockerized-llvm-toolchain/base:${VERSION}
