name: Build and push docker images to the Github Docker registry

on: [ push, pull_request ]

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: base/Dockerfile
          push: true
          tags: dockerized-llvm-toolchain/base:latest

